# Generated by Django 5.2.3 on 2025-07-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_documento', models.FileField(upload_to='documentos_dni/')),
                ('ingresos_documento', models.FileField(upload_to='documentos_ingresos/')),
            ],
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('valido', 'Válido')], default='pendiente', max_length=20),
        ),
    ]
