# Generated by Django 5.2.3 on 2025-07-20 19:40

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario_creado', 'Usuario Creado'), ('politica_actualizada', 'Política Actualizada'), ('backup_completado', 'Backup Completado')], max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
