# Generated by Django 5.2.3 on 2025-07-20 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminlog_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tipo_accion', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('solicitud_creada', 'Solicitud Creada'), ('solicitud_actualizada', 'Solicitud Actualizada'), ('solicitud_aprobada', 'Solicitud Aprobada'), ('solicitud_rechazada', 'Solicitud Rechazada'), ('documento_subido', 'Documento Subido'), ('politica_actualizada', 'Política Actualizada'), ('usuario_creado', 'Usuario Creado'), ('usuario_actualizado', 'Usuario Actualizado'), ('usuario_eliminado', 'Usuario Eliminado'), ('rol_cambiado', 'Rol Cambiado'), ('sistema_backup', 'Backup del Sistema'), ('sistema_restaurado', 'Sistema Restaurado'), ('configuracion_cambiada', 'Configuración Cambiada'), ('acceso_denegado', 'Acceso Denegado')], max_length=50)),
                ('descripcion', models.TextField()),
                ('recurso', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_http', models.CharField(blank=True, max_length=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='exitoso', max_length=20)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('duracion_ms', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='users_audit_timesta_45d1d4_idx'), models.Index(fields=['tipo_accion'], name='users_audit_tipo_ac_47dd4f_idx'), models.Index(fields=['usuario'], name='users_audit_usuario_622fef_idx'), models.Index(fields=['estado'], name='users_audit_estado_2e6c04_idx')],
            },
        ),
    ]
