# Generated by Django 5.2.3 on 2025-07-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('morosidad', 'Alta Morosidad'), ('rendimiento', 'Bajo Rendimiento'), ('cpu', 'Uso de CPU Alto'), ('sistema', 'Problema del Sistema')], max_length=20)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('mensaje', models.TextField()),
                ('valor_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umbral', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email_destinatario', models.EmailField(max_length=254)),
                ('enviado_exitosamente', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta Enviada',
                'verbose_name_plural': 'Alertas Enviadas',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='AlertasConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerta_morosidad', models.DecimalField(decimal_places=2, default=5.0, help_text='Porcentaje de morosidad para activar alerta', max_digits=5)),
                ('alerta_rendimiento', models.DecimalField(decimal_places=2, default=85.0, help_text='Porcentaje mínimo de rendimiento', max_digits=5)),
                ('alerta_cpu', models.DecimalField(decimal_places=2, default=80.0, help_text='Porcentaje máximo de uso de CPU', max_digits=5)),
                ('email_alertas', models.EmailField(default='admin@empresa.com', help_text='Email para recibir notificaciones de alertas', max_length=254)),
                ('alertas_activas', models.BooleanField(default=True, help_text='Si las alertas están habilitadas')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Alertas',
                'verbose_name_plural': 'Configuraciones de Alertas',
            },
        ),
    ]
